language: node_js

node_js:
  - 10

branches:
  only:
    - master
    - next
    - /^greenkeeper.*$/

jobs:
  include:
    - stage: release
      node_js: lts/*
      if: branch = next
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
