language: node_js

node_js:
  - 10
  - 8

jobs:
  include:
    - stage: release
      node_js: lts/*
      on:
        branches: release
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
